amp: true
batch: 16
cache: false
close_mosaic: 10
copy_paste: 0.0
cos_lr: false
data: configs/dataset.yaml
degrees: 5.0
device: 0
epochs: 10
exist_ok: true
fliplr: 0.5
flipud: 0.0
fraction: 1.0
freeze: None
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
imgsz: 640
lr0: 0.001
lrf: 0.01
mixup: 0.0
model: yolov8m.pt
momentum: 0.937
mosaic: 1.0
name: yolov8m_exam
optimizer: AdamW
patience: 50
perspective: 0.0
profile: false
project: outputs
rect: false
resume: false
save: true
save_period: -1
scale: 0.5
shear: 0.0
translate: 0.1
val: true
weight_decay: 0.0005
workers: 8
